# Generated by Django 4.2.6 on 2023-10-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONTACT_EMAIL', models.CharField(help_text='Adresse e-mail de contact par défaut')),
            ],
            options={
                'verbose_name_plural': 'App parameters',
                'db_table': 'tb_app_parameters',
            },
        ),
    ]
