# Generated by Django 4.2.6 on 2023-10-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='sid',
        ),
    ]
