# Generated by Django 4.2.6 on 2023-10-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_remove_badge_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif ?'),
        ),
    ]
