# Generated by Django 4.2.6 on 2023-10-20 22:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('token_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='key',
            field=models.CharField(editable=False, max_length=512, primary_key=True, serialize=False, unique=True, verbose_name='clé'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='magiclinktoken',
            name='end_of_validity',
            field=models.DateTimeField(verbose_name='fin de validité'),
        ),
        migrations.AlterField(
            model_name='magiclinktoken',
            name='key',
            field=models.CharField(editable=False, max_length=512, primary_key=True, serialize=False, unique=True, verbose_name='clé'),
        ),
        migrations.AlterField(
            model_name='magiclinktoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magiclink_tokens', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='passwordlesstoken',
            name='end_of_validity',
            field=models.DateTimeField(verbose_name='fin de validité'),
        ),
        migrations.AlterField(
            model_name='passwordlesstoken',
            name='key',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6), django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='clé'),
        ),
        migrations.AlterField(
            model_name='passwordlesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwordless_tokens', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
