# Generated by Django 4.2.7 on 2023-12-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiaccesstoken',
            old_name='end_of_validity',
            new_name='expiration',
        ),
        migrations.RenameField(
            model_name='loginpasswordlesstoken',
            old_name='end_of_validity',
            new_name='expiration',
        ),
        migrations.RenameField(
            model_name='magiclinktoken',
            old_name='end_of_validity',
            new_name='expiration',
        ),
        migrations.RenameField(
            model_name='signuppasswordlesstoken',
            old_name='end_of_validity',
            new_name='expiration',
        ),
    ]
