# Generated by Django 4.2.7 on 2023-11-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiclinktoken',
            name='usage',
            field=models.CharField(choices=[('auth/classic/reset-password', 'Reset Password')], max_length=1024),
        ),
        migrations.DeleteModel(
            name='PasswordLessToken',
        ),
    ]
