# Generated by Django 4.2.7 on 2023-11-30 10:20

import core.utils.string_utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('token_auth', '0002_alter_magiclinktoken_usage_delete_passwordlesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePasswordLessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(db_index=True, default=core.utils.string_utils.get_secret_id, editable=False, unique=True)),
                ('created', models.DateTimeField(editable=False, verbose_name='Création')),
                ('modified', models.DateTimeField(editable=False, verbose_name='Modification')),
                ('end_of_validity', models.DateTimeField(verbose_name='fin de validité')),
                ('key', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6), django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='clé')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignupPasswordLessToken',
            fields=[
                ('basepasswordlesstoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='token_auth.basepasswordlesstoken')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'tb_future_user_password_less_tokens',
            },
            bases=('token_auth.basepasswordlesstoken',),
        ),
        migrations.CreateModel(
            name='PasswordLessToken',
            fields=[
                ('basepasswordlesstoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='token_auth.basepasswordlesstoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwordless_tokens', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'db_table': 'tb_password_less_tokens',
            },
            bases=('token_auth.basepasswordlesstoken',),
        ),
    ]
