# Generated by Django 4.2.7 on 2023-12-01 16:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('token_auth', '0002_rename_end_of_validity_apiaccesstoken_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccesstoken',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='apiaccesstoken',
            name='expiration',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='apiaccesstoken',
            name='key',
            field=models.CharField(editable=False, max_length=512, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='apiaccesstoken',
            name='modified',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='apiaccesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginpasswordlesstoken',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='loginpasswordlesstoken',
            name='expiration',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='loginpasswordlesstoken',
            name='key',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6), django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='loginpasswordlesstoken',
            name='modified',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='loginpasswordlesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwordless_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='magiclinktoken',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='magiclinktoken',
            name='expiration',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='magiclinktoken',
            name='key',
            field=models.CharField(editable=False, max_length=512, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='magiclinktoken',
            name='modified',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='magiclinktoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magiclink_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signuppasswordlesstoken',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='signuppasswordlesstoken',
            name='expiration',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='signuppasswordlesstoken',
            name='key',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6), django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='signuppasswordlesstoken',
            name='modified',
            field=models.DateTimeField(editable=False),
        ),
    ]
