# Generated by Django 4.2.7 on 2023-11-30 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('token_auth', '0003_basepasswordlesstoken_futureuserpasswordlesstoken_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordLessToken',
            new_name='LoginPasswordLessToken',
        ),
        migrations.AlterModelTable(
            name='loginpasswordlesstoken',
            table='tb_login_password_less_tokens',
        ),
        migrations.AlterModelTable(
            name='signuppasswordlesstoken',
            table='tb_signup_password_less_tokens',
        ),
    ]
