# Generated by Django 4.2.7 on 2023-12-01 08:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('token_auth', '0004_rename_passwordlesstoken_loginpasswordlesstoken_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIToken',
            new_name='APIAccessToken',
        ),
    ]
