# Generated by Django 4.2.7 on 2023-12-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0005_rename_apitoken_apiaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccesstoken',
            name='end_of_validity',
            field=models.DateTimeField(default=None, verbose_name='fin de validité'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='apiaccesstoken',
            table='tb_api_access_tokens',
        ),
    ]
