# Generated by Django 4.2.7 on 2023-12-01 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('token_auth', '0006_apiaccesstoken_end_of_validity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccesstoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_access_token', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
