# Generated by Django 4.2.7 on 2023-12-01 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('token_auth', '0007_alter_apiaccesstoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access_tokens', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
