# Generated by Django 4.2.6 on 2023-10-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSkeleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=512, unique=True)),
                ('subject', models.CharField(max_length=998, verbose_name='sujet')),
                ('html_body', models.TextField(verbose_name='body HTML')),
                ('send_mode', models.CharField(choices=[('to', 'To'), ('bcc', 'Bcc')], max_length=512, verbose_name="mode d'envoi")),
            ],
            options={
                'db_table': 'tb_mail_datas',
            },
        ),
    ]
