# Generated by Django 4.0.4 on 2022-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSkeleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=512, unique=True)),
                ('subject', models.CharField(max_length=998)),
                ('html_body', models.TextField()),
                ('send_mode', models.CharField(choices=[('to', 'To'), ('bcc', 'Bcc')], max_length=512)),
            ],
            options={
                'db_table': 'tb_mail_datas',
            },
        ),
    ]
