# Generated by Django 4.2.7 on 2023-12-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailskeleton',
            name='html_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mailskeleton',
            name='send_mode',
            field=models.CharField(choices=[('to', 'To'), ('bcc', 'Bcc')], max_length=512),
        ),
        migrations.AlterField(
            model_name='mailskeleton',
            name='subject',
            field=models.CharField(max_length=998),
        ),
    ]
