# Generated by Django 4.2.6 on 2023-10-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailskeleton',
            name='html_body',
            field=models.TextField(verbose_name='body HTML'),
        ),
        migrations.AlterField(
            model_name='mailskeleton',
            name='send_mode',
            field=models.CharField(choices=[('to', 'To'), ('bcc', 'Bcc')], max_length=512, verbose_name="mode d'envoi"),
        ),
        migrations.AlterField(
            model_name='mailskeleton',
            name='subject',
            field=models.CharField(max_length=998, verbose_name='sujet'),
        ),
    ]
